# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/capstone_dir/riscv-project-dev/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/capstone_dir/riscv-project-dev/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/capstone_dir/riscv-project-dev/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {{E:/capstone_dir/riscv-project-dev/RTL files/design srcs/CSR_ADDR.vh}}
set_property file_type "Verilog Header" [get_files {{E:/capstone_dir/riscv-project-dev/RTL files/design srcs/CSR_ADDR.vh}}]
read_verilog -library xil_defaultlib {
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/CSR.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/EX.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/Forwarding_unit.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/ID.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/IF.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/Instruction_mem.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/LU.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/MEM.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/WB.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/alu.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/alu_control.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/bus_arbiter.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/control_unit.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/data_mem.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/hazard_detection_unit.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/processor.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/reg_file.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/sign_ext.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/uart_tx.v}
  {E:/capstone_dir/riscv-project-dev/RTL files/design srcs/SOC.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/capstone_dir/riscv-project-dev/project_1/project_1.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files E:/capstone_dir/riscv-project-dev/project_1/project_1.srcs/constrs_1/new/constr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top SOC -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SOC.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SOC_utilization_synth.rpt -pb SOC_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
